export enum PROGRAM_TYPES {
  EXAMPLE_DETAIL = "EXAMPLE_DETAIL",
  EXAMPLE_FORM = "EXAMPLE_FORM",
  EXAMPLE_LIST = "EXAMPLE_LIST",
  EXAMPLE_LIST_AND_DRAWER = "EXAMPLE_LIST_AND_DRAWER",
  EXAMPLE_LIST_AND_MODAL = "EXAMPLE_LIST_AND_MODAL",
  EXAMPLE_LIST_WITH_FORM = "EXAMPLE_LIST_WITH_FORM",
  EXAMPLE_LIST_WITH_FORM_ROW = "EXAMPLE_LIST_WITH_FORM_ROW",
  EXAMPLE_LIST_WITH_FORM_LIST = "EXAMPLE_LIST_WITH_FORM_LIST",
  EXAMPLE_LIST_WITH_LIST = "EXAMPLE_LIST_WITH_LIST",
  EXAMPLE_THREE_LIST = "EXAMPLE_THREE_LIST",
  EXAMPLE_STATS = "EXAMPLE_STATS",

  /* ##ADD_PROGRAM_TYPE_POSITION## */
}
